language: php

services:
  - mysql

cache:
  directories:
    - $HOME/.composer/cache


php:
  - 7.4snapshot
  - 7.3

# Test against the latest version of WordPress and one version back.
env:
  - WP_VERSION=latest


matrix:
  fast_finish: true
  include:
    - name: Coding standards
      php: 7.3
      env: WP_VERSION=latest

  
  allow_failures:
    - name: Bleeding edge

before_install:
  - export PATH="$HOME/.composer/vendor/bin:$PATH"

  # Unless we need XDebug, disable it for improved performance.
  - phpenv config-rm xdebug.ini || return 0

install:
  # Install our Composer dependencies
  - composer install --prefer-dist --no-interaction

  # Install the WordPress core test suite
  - bash bin/install-wp-tests.sh wordpress_test root '' localhost $WP_VERSION

script:
  - |
    # If we've set the $WP_TRAVISCI variable to run PHPCS, do that instead
    # of running PHPUnit.
    if [[ "$WP_TRAVISCI" == "phpcs" ]]; then
      ./vendor/bin/phpcs

    else
      # Execute the test suite
      ./vendor/bin/phpunit

      # Optionally run the tests again in a multisite environment
      #WP_MULTISITE=1 ./vendor/bin/phpunit
    fi